### ISSUE TITLE
Script keeps crashing

### ISSUE THREAD

**Issue by leonfox** [franciscod/telegram-twitter-forwarder-bot#10]
Either TWITTER_ACCESS_TOKEN or TWITTER_ACCESS_TOKEN_SECRET environment variables are missing. Tweepy will be initialized in 'app-only' mode
2016-08-16 15:02:22,680 - TwitterForwarderBot - INFO - Initializing
2016-08-16 15:02:22,680 - JobQueue - DEBUG - Putting a FetchAndSendTweetsJob with t=0
2016-08-16 15:02:22,681 - JobQueue - DEBUG - Ticking jobs with t=1471377742.6814742
2016-08-16 15:02:22,681 - JobQueue - DEBUG - Peeked a FetchAndSendTweetsJob with t=0
2016-08-16 15:02:22,681 - JobQueue - DEBUG - About time! running
2016-08-16 15:02:22,681 - FetchAndSendTweetsJob - DEBUG - Fetching tweets...
2016-08-16 15:02:22,682 - JobQueue - DEBUG - Putting a FetchAndSendTweetsJob with t=1471377862.6814742
2016-08-16 15:02:22,682 - JobQueue - DEBUG - Peeked a FetchAndSendTweetsJob with t=1471377862.6814742
2016-08-16 15:02:22,682 - JobQueue - DEBUG - Next task isn't due yet. Finished!
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    bot.kb_interruptable_loop()
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/basebot.py", line 161, in kb_interruptable_loop
    self.loop()
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/basebot.py", line 151, in loop
    self.poll()
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/basebot.py", line 74, in poll
    upds = self.tg.getUpdates(offset=self.update_offset, timeout=self.POLL_TIMEOUT)
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/venv/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/venv/lib/python3.4/site-packages/telegram/bot.py", line 697, in getUpdates
    return [Update.de_json(x) for x in result]
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/venv/lib/python3.4/site-packages/telegram/bot.py", line 697, in <listcomp>
    return [Update.de_json(x) for x in result]
  File "/home/leonfox/Telegram-Twitter/telegram-twitter-forwarder-bot/venv/lib/python3.4/site-packages/telegram/update.py", line 58, in de_json
    data['message'] = Message.de_json(data['message'])
KeyError: 'message'

**Comment by leonfox** [comment]
I guess I should note the environment! This is Python 3.4.2 on Debian Jessie and I followed the instructions and installed the required python packages via pip into my virtual python environment.

**Comment by franciscod** [comment]
Try updating python-telegram-bot to the latest version. If you send a PR
I'd merge it right away!

**Comment by leonfox** [comment]
Yeah, looks like the solution was: pip install python-telegram-bot --upgrade

**Comment by franciscod** [comment]
I'll close this one :)
