### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'safe_create_index'

### ISSUE THREAD

**Issue by Adem1987** [franciscod/telegram-twitter-forwarder-bot#39]
I'm getting this error on Debian in a virtualenvironment.

`$ python main.py 
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from bot import TwitterForwarderBot
  File "/home/adem/twitterbot/bot.py", line 10, in <module>
    from models import TelegramChat, TwitterUser
  File "/home/adem/twitterbot/models.py", line 90, in <module>
    t.create_table(fail_silently=True)
  File "/home/adem/twitterbot/venv2/lib/python3.5/site-packages/peewee.py", line 5665, in create_table
    if safe and not cls._meta.database.safe_create_index \
AttributeError: 'NoneType' object has no attribute 'safe_create_index'`

I don't know, what to do.

**Comment by franciscod** [comment]
Hey, it's been a few years :) Do you still experience this?

**Comment by franciscod** [comment]
I've just updated most of the project's dependencies. I'd assume this is now fixed!
