### ISSUE TITLE
error when running main.py

### ISSUE THREAD

**Issue by MichelangeloNigro** [franciscod/telegram-twitter-forwarder-bot#50]
hi, i get this error when i try to run the main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import tweepy
  File "/home/ubuntu/Desktop/telegram-twitter-forwarder-bot-master/venv/lib/python3.8/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/home/ubuntu/Desktop/telegram-twitter-forwarder-bot-master/venv/lib/python3.8/site-packages/tweepy/streaming.py", line 340
    def _start(self, async):
                     ^
SyntaxError: invalid syntax
any suggestion on how to fix it?

**Comment by franciscod** [comment]
Looks like we should update tweepy: `async` is now a keyword in Python

**Comment by Igen99** [comment]
Alright, so I should wait for you to update it?

**Comment by franciscod** [comment]
I'd accept a PR doing it :)

**Comment by Igen99** [comment]
A PR?

**Comment by franciscod** [comment]
I've just updated most of the project's dependencies, including tweepy. This is now fixed!
