### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by AnakTeka** [franciscod/telegram-twitter-forwarder-bot#8]
Hi, I have been using this bot for awhile and works perfectly, but suddenly today the bot refused to work, it is still able to fetch new tweets but it wont keep running, it just stopped after sent tweets to me.

```
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    bot.kb_interruptable_loop()
  File "/home/yoga/opt/python/kenaparusak/basebot.py", line 161, in kb_interruptable_loop
    self.loop()
  File "/home/yoga/opt/python/kenaparusak/basebot.py", line 151, in loop
    self.poll()
  File "/home/yoga/opt/python/kenaparusak/basebot.py", line 74, in poll
    upds = self.tg.getUpdates(offset=self.update_offset, timeout=self.POLL_TIMEOUT)
  File "/home/yoga/opt/python/venv/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/yoga/opt/python/venv/lib/python3.4/site-packages/telegram/bot.py", line 697, in getUpdates
    return [Update.de_json(x) for x in result]
  File "/home/yoga/opt/python/venv/lib/python3.4/site-packages/telegram/bot.py", line 697, in <listcomp>
    return [Update.de_json(x) for x in result]
  File "/home/yoga/opt/python/venv/lib/python3.4/site-packages/telegram/update.py", line 58, in de_json
    data['message'] = Message.de_json(data['message'])
KeyError: 'message'
```

**Comment by franciscod** [comment]
Sorry I haven't looked at this!

Try updating to the latest version of  python-telegram-bot. Telegram
introduced breaking changes where the "message" field is now optional and
that broke a lot of APIs. It should work of you update that dependency.

Bonus points if you send a PR bumping the version to the latest one in
requirements.txt ;)
